### ISSUE TITLE
QGIS 3

### ISSUE THREAD

**Issue by alexmodesto73** [NaturalGIS/geotag_and_import_photos#15]
Is qgis 3 support planned?

**Comment by gioman** [comment]
@alexmodesto73 yes.

**Comment by jdlom** [comment]
Any info on the release date ? Need help ?

**Comment by luipir** [comment]
Hi @lejedi76 do you know that you can import geotagged photo directly from qgis processing toolbox?

look for "Import geotagged photos"

this is the help:

"Import geotagged photos
Creates a point layer corresponding to the geotagged locations from JPEG images from a source folder. Optionally the folder can be recursively scanned.
The point layer will contain a single PointZ feature per input file from which the geotags could be read. Any altitude information from the geotags will be used to set the point's Z value.
Optionally, a table of unreadable or non-geotagged photos can also be created."

**Comment by gioman** [comment]
> do you know that you can import geotagged photo directly from qgis processing toolbox?

@luipir true, but this plugin does much more (add coordinates to photos that are not geotagged, add custom tags to photos, and more), and maybe this is what @lejedi76 needs.

**Comment by gioman** [comment]
> Any info on the release date ? Need help ?

@lejedi76 is still on the TODO list, but contributions are always welcome (and contributors always credited),
